import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readJson,validateData} from './knowledge.mjs';
import {prepareImport} from './import-node.mjs';
const data=readJson('data/evidence.json'),profiles=readJson('data/node-profiles.json'),config=readJson('config/network.json');
function fixture(){return {node:{id:'Test entity',label:'Test entity',kind:'organization',subtitle:'Test-only fixture',summary:'This is a synthetic fixture used only by automated tests to verify complete node imports without modifying live data.',sources:['M1'],updated:'2026-09-14'},sources:[],connections:[{id:'TEST-EDGE',source:'Test entity',target:'METR',relation:'Synthetic test connection',type:'access',date:'2026-09-14',evidence:'documented',sources:['M1']}],views:['metr']};}
test('one packet adds profile, edges and view membership without mutating inputs',()=>{const result=prepareImport(data,profiles,config,fixture());assert.ok(result.profiles['Test entity']);assert.ok(result.config.views.metr.seeds.includes('Test entity'));assert.deepEqual(validateData(result.data,result.profiles,result.config),[]);assert.equal(profiles['Test entity'],undefined);assert.ok(!config.views.metr.seeds.includes('Test entity'));});
test('import rejects duplicates and missing endpoints',()=>{const duplicate=fixture();duplicate.node.id='METR';assert.throws(()=>prepareImport(data,profiles,config,duplicate),/already exists/);const broken=fixture();broken.connections[0].target='Absent';assert.throws(()=>prepareImport(data,profiles,config,broken),/missing endpoint/);});
test('invalid view and incomplete profile cannot be imported',()=>{const packet=fixture();packet.views=['unknown'];assert.throws(()=>prepareImport(data,profiles,config,packet),/Unknown/);packet.views=[];delete packet.node.subtitle;assert.throws(()=>prepareImport(data,profiles,config,packet),/subtitle required/);});
test('the unfinished template is never accepted as real evidence',()=>assert.throws(()=>prepareImport(data,profiles,config,readJson('examples/node.template.json'))));
test('new relationship styles and focus views are configuration-only',()=>{const c=structuredClone(config),packet=fixture();c.relationshipTypes.example={label:'Example relationship',color:'#123456'};c.views.example={label:'Example focus',seeds:[]};packet.connections[0].type='example';packet.views=['example'];const r=prepareImport(data,profiles,c,packet);assert.deepEqual(validateData(r.data,r.profiles,r.config),[]);});
